# See for reference: https://aka.ms/yaml

# Trigger builds for all commits to master, and all PRs
trigger: [master]

jobs:
- job: check_formatting
  displayName: Check formatting
  pool:
      vmImage: ubuntu-16.04
  steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      $HOME/.cargo/bin/rustup component add rustfmt
    displayName: Install Rust stable
  - script: |
      cd binary
      $HOME/.cargo/bin/cargo fmt -- --check
    displayName: Run rustfmt

- template: ./azure-pipelines-template.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: ./azure-pipelines-template.yml
  parameters:
    name: macOS
    vmImage: macOS-10.13
